### ISSUE TITLE
Unable to pair with Google Home

### ISSUE THREAD

**Issue by mfucci** [mfucci/node-matter#140]
Steps to reproduce:
- launch Google Home
- click "+" / "set up device" to add a new device
- Select "New device"
- Select location then click "next"
- Wait until it times out to find a new device
- Click "Matter-enabled device"
- Scan node-matter QR code
- Click "I agree" to accept Google Home role
- "Connecting device to Google Home..." fails after a timeout "Can't find your device"

**Comment by mfucci** [comment]
From Wireshark, the issue might be that node-matter doesn't support IPv6 yet.
I will add the support for it this week then...

**Comment by andyearnshaw** [comment]
Have you added the matter device in Google Home Developer Console? I'm not 100% certain, but it is implied that test vendor/product IDs will only show up if you do this.

> Any Matter device that has passed CSA Matter certification works in the Google Home ecosystem.

(implies that any device that hasn't passed certification will not work)

> Reboot your hub to ensure that it receives the most recent Matter integration project configuration. If you have to change the VID or PID later, you'll also need to reboot after saving the project for the change to take effect.

(implies that Google Home will download the developer console configuration on reboot)

https://developers.home.google.com/codelabs/matter-device-virtual#2

**Comment by mfucci** [comment]
I did not added up in Google Home Developer Console.

The troubles I have:

1. the "Add a Matter Device" is now gone in Google Home on my main phone. Before it was gone, I was able to pair the CHIP lighting app (but appeared afterward as unreachable) but not node-matter
2. I revived an old Android phone: "Add a Matter Device" is not in Google Home as well but "Matter devices" is in Settings app > Google > Devices & sharing. Pairing the CHIP lighting app fails after a few exchanges, when trying to pair node-matter, Android doesn't even try to connect so something is wrong from the start.
3. Pairing from chip-tool is still working fine
4. I have now added IPv6 support so this is not the issue

@andyearnshaw : if you have some time, can you try compiling CHIP lighting app and pair it with your phone (Android or iOs)?
I would love to know a working configuration...

**Comment by JimBuzbee** [comment]
Regarding the "Add a Matter Device" going missing. You can get it back by opening the camera app, focusing on the node-matter QR code and then pressing the "Tap to Set Up" button that appears. This will go through the same sequence as usual from Google home. Then the button will also appear as it previously did in the Google Home setup. At least until Google pushes another update. Unfortunately, the setup still fails with a lot of debug messages on screen.

**Comment by mfucci** [comment]
Thanks for the tip!
Yes, that did the trick: I can now try to pair again from my main phone!
Still not working though, digging through Wireshark logs now

**Comment by mfucci** [comment]
In the Android logs, there is an error : "Commissioning failed with state Failure obtaining credentials."

I now added the VID and PID in Google Home Developer Console but that didn't fix the issue.

The failure seems to be because of a Timeout rather then test credentials missing, I think...

@andyearnshaw @JimBuzbee : where you able to pair CHIP lightning app or a virtual device?
If yes, which instructions did you follow?

**Comment by JimBuzbee** [comment]
I'm a novice at this and have only tried to pair with Google Home and with the Android Alexa app. I've not been successful with either. Here's the output when trying to pair with Alexa:

2022-11-4 19:39:17.534 INFO Device node-matter@0.0.11
2022-11-4 19:39:17.547 INFO Device Listening
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ ██▀▄▀▄█ ▄▄▄▄▄ █
█ █   █ █▄▀▄▀▄█ █   █ █
█ █▄▄▄█ ██ ▀▀▄█ █▄▄▄█ █
█▄▄▄▄▄▄▄█ █ ▀▄█▄▄▄▄▄▄▄█
█   █  ▄▄ ▀ █  ▄▀██ █▀█
█▀ ███▀▄▄▀█  ▀▄▄██▄▀█▀█
████▄██▄▄██▄▀ ▀██▄▀ ▄▀█
█ ▄▄▄▄▄ █ █▄█▄█▄▄█▀██ █
█ █   █ █▄▄██▄ ▄█▀▄▄▀██
█ █▄▄▄█ █ ▀ █▄█ ▀▀ ▀▀ █
█▄▄▄▄▄▄▄█▄█▄█▄████▄▄█▄█
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀

QR Code URL: https://project-chip.github.io/connectedhomeip/qrcode.html?data=MT:-24J0AFN00KA0648G00
Manual pairing code: 34970112332
2022-11-4 19:39:17.549 ERROR MdnsBroadcaster Error: send EMSGSIZE ff02::fb:5353



2022-11-4 19:40:35.763 DEBUG MessageExchange onMessageReceived id:0/39861/53639255 t:0/32 reqAck:true payload: 15300120142ff9b9b17dab4a8cc9ce35d10a0ac6d479a041e74a285d06b92f000849a6d125024d11240300280418
2022-11-4 19:40:35.765 INFO PaseServer Pase server: Received pairing request from udp://192.168.1.44:5541
2022-11-4 19:40:35.768 DEBUG ExchangeManager sending id:0/39861/1875800731 t:0/33 acked:53639255 reqAck:true payload: 15300120142ff9b9b17dab4a8cc9ce35d10a0ac6d479a041e74a285d06b92f000849a6d13002209b7dec9ec007ff6b7ae1d4ed2f1d8aea7e3601ea4e5ad55c5d5547dffad041a325035c5e35042501e803300220d32014b423023625731ae603911844634568839becf37028ef49d4fc55f5d0ba1818
2022-11-4 19:40:35.785 DEBUG MessageExchange onMessageReceived id:0/39861/53639256 t:0/16 acked:1875800731 reqAck:false payload:
2022-11-4 19:40:35.865 DEBUG MessageExchange onMessageReceived id:0/39861/53639257 t:0/34 acked:1875800731 reqAck:true payload: 15300141047d1dd9853006379d1e63f5d603d23915f3aa3d2a41809369f0afb01a67fcbf251343d530153a16efa849e4ba154bc99bf065df5d7078c11eebefa7c508b8c8dc18
2022-11-4 19:40:35.905 DEBUG ExchangeManager sending id:0/39861/1875800732 t:0/35 acked:53639257 reqAck:true payload: 1530014104699d72603dcf1ebbe0a45a3e0f9fea3a09cf9e3dd0c5f11a49bb21f87670c3365c362fc2a519ed3cba3f9a1a996d00960db1784dde01869e0532798fb243eb2f300220e3fe67a01d6e91595c664944862ef56be8c24aa9bf5e43b40ab4b6ecfebbbd7f18
2022-11-4 19:40:35.921 DEBUG MessageExchange onMessageReceived id:0/39861/53639258 t:0/16 acked:1875800732 reqAck:false payload:
2022-11-4 19:40:35.993 DEBUG MessageExchange onMessageReceived id:0/39861/53639259 t:0/36 acked:1875800732 reqAck:true payload: 1530012032f85f36e849481862ca0cae47fbfa2b05c806ac0a315dae6830ecf10e002d5118
2022-11-4 19:40:35.994 DEBUG ExchangeManager sending id:0/39861/1875800733 t:0/64 acked:53639259 reqAck:true payload: 0000000000000000
2022-11-4 19:40:36.016 DEBUG MessageExchange onMessageReceived id:0/39861/53639260 t:0/16 acked:1875800733 reqAck:false payload:
2022-11-4 19:40:36.016 INFO PaseServer Pase server: session 24156 created with udp://192.168.1.44:5541
2022-11-4 19:40:36.115 DEBUG MessageExchange onMessageReceived id:24156/39862/180847106 t:1/10 reqAck:true payload: 152500102724ff0118
2022-11-4 19:40:36.117 ERROR InteractionMessenger Error: Unsupported message type 10
    at InteractionServerMessenger.<anonymous> (/Users/jimbuzbee/matter/node-matter/build/matter/interaction/InteractionMessenger.js:80:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jimbuzbee/matter/node-matter/build/matter/interaction/InteractionMessenger.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-4 19:40:36.117 DEBUG ExchangeManager sending id:24156/39862/1875800734 t:1/1 acked:180847106 reqAck:true payload: 1524000124ff0118
2022-11-4 19:40:36.172 DEBUG MessageExchange onMessageReceived id:24156/39862/180847107 t:0/16 acked:1875800734 reqAck:false payload:
2022-11-4 19:40:51.464 DEBUG MessageExchange onMessageReceived id:0/39863/53639261 t:0/32 reqAck:true payload: 15300120302f5643efe0bed155112015d7e681f522337c10e8d059c242f20efe822a1c6525024e11240300280418
2022-11-4 19:40:51.464 INFO PaseServer Pase server: Received pairing request from udp://192.168.1.44:5541
2022-11-4 19:40:51.465 DEBUG ExchangeManager sending id:0/39863/1875800735 t:0/33 acked:53639261 reqAck:true payload: 15300120302f5643efe0bed155112015d7e681f522337c10e8d059c242f20efe822a1c653002202e08757adde8ffc6eb03a9677371af84fe7c20b6910e7a4c6dcf236b60ca3d5a25035d5e35042501e803300220d32014b423023625731ae603911844634568839becf37028ef49d4fc55f5d0ba1818
2022-11-4 19:40:51.486 DEBUG MessageExchange onMessageReceived id:0/39863/53639262 t:0/16 acked:1875800735 reqAck:false payload:
2022-11-4 19:40:51.563 DEBUG MessageExchange onMessageReceived id:0/39863/53639263 t:0/34 acked:1875800735 reqAck:true payload: 1530014104e5fb98d7878400d7ff04aacc00182e155e3bc81821804f8e92cacdc44544e733acf0881a6634c5cfb52a70720fb8ce75ce545d7a363d16254202dd62017b87c618
2022-11-4 19:40:51.600 DEBUG ExchangeManager sending id:0/39863/1875800736 t:0/35 acked:53639263 reqAck:true payload: 153001410420babd73930d1bdb9b0a71b83330a2a59dd30be8f99c2019aab2c33c2a5b6c44ab26182b8e8b45aa03a33783e3e0fc7e57b7ff366ff3bce2085f83505f083c5b30022073e49f3f7233208dbeac5f7c661a64a0dc8847a6f07c7cae78951215bc2eaa1418
2022-11-4 19:40:51.616 DEBUG MessageExchange onMessageReceived id:0/39863/53639264 t:0/16 acked:1875800736 reqAck:false payload:
2022-11-4 19:40:51.688 DEBUG MessageExchange onMessageReceived id:0/39863/53639265 t:0/36 acked:1875800736 reqAck:true payload: 15300120d49af0c59e0b15978fa846c6e05154f88fcc67a99689bc7e6e05a0187437f42218
2022-11-4 19:40:51.688 DEBUG ExchangeManager sending id:0/39863/1875800737 t:0/64 acked:53639265 reqAck:true payload: 0000000000000000
2022-11-4 19:40:51.709 DEBUG MessageExchange onMessageReceived id:0/39863/53639266 t:0/16 acked:1875800737 reqAck:false payload:
2022-11-4 19:40:51.709 INFO PaseServer Pase server: session 24157 created with udp://192.168.1.44:5541
2022-11-4 19:40:51.809 DEBUG MessageExchange onMessageReceived id:24157/39864/59025 t:1/10 reqAck:true payload: 152500102724ff0118
2022-11-4 19:40:51.809 ERROR InteractionMessenger Error: Unsupported message type 10
    at InteractionServerMessenger.<anonymous> (/Users/jimbuzbee/matter/node-matter/build/matter/interaction/InteractionMessenger.js:80:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jimbuzbee/matter/node-matter/build/matter/interaction/InteractionMessenger.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-11-4 19:40:51.810 DEBUG ExchangeManager sending id:24157/39864/1875800738 t:1/1 acked:59025 reqAck:true payload: 1524000124ff0118
2022-11-4 19:40:51.827 DEBUG MessageExchange onMessageReceived id:24157/39864/59026 t:0/16 acked:1875800738 reqAck:false payload:

**Comment by mfucci** [comment]
Thanks for testing!
The bug you have above is fixed in a PR not merged yet. Look at the PR saying TimedRequest and sync to that branch.

Were you able to get the config giving by Andy working?
https://developers.home.google.com/codelabs/matter-device-virtual#2

I think I am stuck at the point where Google Home is expecting credentials to be provisioned in the dev console in all my configurations...

**Comment by mfucci** [comment]
Hi Jim,

Looks like you are able to go further in the pairing flow than me!
I am stuck at 0/62/4 command, Google Home says "Something went wrong" after that.

Can you help me reproduce your configuration so I can debug from there?

I will need those info:

- version of Google Home app? I have 2.62.80.2
- version of Home service? I have v224814000 (command "adb shell dumpsys activity provider com.google.android.gms.chimera.container.GmsModuleProvider | grep "com.google.android.gms.home")
- do you set something in Google Home Dev Console? If yes, which name / vendor ID / product ID
- do you have a Google Matter-compatible device in your house? On my side, I have a Google Nest speaker but I have no clue if it is Matter-compatible

Thanks!
- Marco

**Comment by JimBuzbee** [comment]
Marco - To be clear, the long debug output is not from my Google Home. It's from the Amazon Alexa app running on Android when I try and add the node-matter "device".  I've tried both Google Home and Alexa. I think I get similar behavior to you on Google Home.

**Comment by mfucci** [comment]
Sorry, I missed that part...

Can you create a new bug "Pairing with Alexa not working" with your logs above so I can work on it in parallel?

Thanks!
- Marco

**Comment by andyearnshaw** [comment]
Apologies, I'm temporarily without a personal computer so am unable to contribute at present.

**Comment by mfucci** [comment]
Google just pushed an update (com.google.android.gms.home [v224915000]) so things are working much better.
I am now able to pair the example from the official codebase and node-matter is going a little further in the pairing flow.

I will probably have node-matter pairing with Android  by the end of the week.

**Comment by mfucci** [comment]
Seems like it was easier than I thought. After fixing one bug and adding the implementation for one additional cluster, I am now able to pair node-matter from Google Home: branch [add-android-support](https://github.com/mfucci/node-matter/tree/add-android-support)

It appears as "offline" so I cannot operate it after pairing, but I think this is due to a misconfiguration of my Nest Speaker: I will investigate this tomorrow.

**Comment by mfucci** [comment]
I can now pair but there is some issues to control it after pairing.
The hub subscribe to */*/* (all attributes from all clusters from all endpoints) instead of just the one it needs and node-matter incorrectly assumes that it is possible to subscribe to all attributes, which is not the case, which is not the case.

So I need to:

- refactor all cluster definitions to clearly declare which ones can be subscribe to
- add support in the server to pass the subscribe info
- when a client asks to subscribe to */*/*, filter attributes based on if they can be subscribe to or not.

**Comment by Apollon77** [comment]
I take csare about first todo today

**Comment by Apollon77** [comment]
@mfucci Verified for the existing clusters ... only the onoff attrible of onoff is "reportable" for now (BUT the specs do not contain this, but the chip XML file does, so it is already in our code as comment "reportable: true".

**Comment by Apollon77** [comment]
Ahh ... ok then I think we misunderstood that ... Thank you!

@mfucci I will have a look but I did not discovered "changes omitted" so far in any of our defined-out clusters ...

**Comment by mfucci** [comment]
@bzbarsky-apple : thanks for clarifying the expected behavior!
That was not my understanding but this actually match the current implementation in node-matter: since "reportable" or "changes ommitted" were not implemented, all attributes can be subscribed to and changes will be reported.

However chunking is not implemented either, and reporting all attributes in one message probably goes beyond the max length. I will work on adding this mechanism then. Alexa and Home Assistant only subscribe to onoff attribute so don't trigger this issue.

**Comment by mfucci** [comment]
Chunking implemented! It was actually easier than I thought: https://github.com/mfucci/node-matter/pull/176

node-matter is now working with Android!!!!!
Closing this issue.

![Screenshot_20230106-223930](https://user-images.githubusercontent.com/154627/211141912-08cb128c-b23b-4778-9d88-5d0070472fdc.png)

**Comment by Apollon77** [comment]
btw: do we know if Google home on ios also works? Else I can also test that later
