### ISSUE TITLE
Node-Red module

### ISSUE THREAD

**Issue by xtvdata** [mfucci/node-matter#146]
Hi,
just a proposal, wouldn't it be useful to have a small module (node) for **Node-Red** to wrap `node-matter` features?

Since we are in a quickly evolving scenario, It would allow to easily test devices and features in a controlled environment.

**Comment by Apollon77** [comment]
As soon as it is really working to "Build devices that can be paired" (we are still on that) yes it is on the todo List. if you want to take over such a topic fel free to comment in https://github.com/mfucci/node-matter/discussions/39
