### ISSUE TITLE
Operational Credentials(0x3e)/currentFabricIndex(0x5) not implemented (crashes iOS)

### ISSUE THREAD

**Issue by Apollon77** [mfucci/node-matter#183]
2023-0-0 17:56:51.028 DEBUG InteractionProtocol Received read request from udp://fe80::141c:e38b:5593:10e3%en0:60357 on session secure/32461: MA-rootdevice(0x0)/Operational Credentials(0x3e)/currentFabricIndex(0x5)

More details see https://github.com/mfucci/node-matter/issues/181#issue-1524591273

**Comment by Apollon77** [comment]
@mfucci as assumed:

When I set the currentFabricIndex to the index of the added Fabric when adding it in addOperationalCert then this ID is sent for the removeFarbic instead of 0 ... which feels way more correct.

Now we would continue in https://github.com/mfucci/node-matter/issues/185

**Comment by mfucci** [comment]
Operational Credentials(0x3e)/currentFabricIndex(0x5) is not implemented.
By default, it returns 0 which is incorrect so this prevent the pairing.

Home on my iPhone seems to have been updated as well on my side, so I now have the same issue.
I will send a PR to fix this shortly: this will require to full implement fabric-scoped attribute values...

**Comment by mfucci** [comment]
This is now merged. Can you check on the latest version if you still have this issue?

Note: other issues are currently preventing pairing from iOS but this one should be addressed
