### ISSUE TITLE
Add some example / quick start code?

### ISSUE THREAD

**Issue by flatsiedatsie** [mfucci/node-matter#210]
Thank you for your wonderful work.

As a small suggestion, it would rock if you could share some example code to help people (like me) quickly get started and play around.

**Comment by Apollon77** [comment]
Code wise we are not yet there, for now you can look into Device.ts, but much stuff is needed right now. We work on a better high level API

**Comment by Apollon77** [comment]
continue in https://github.com/mfucci/node-matter/discussions/151
