### ISSUE TITLE
Implement the Temperature Measurement Cluster

### ISSUE THREAD

**Issue by JimBuzbee** [mfucci/node-matter#211]
Implement as specified in section 2.3 of the _Matter Application Cluster Specification Version 1.0_

**Comment by JimBuzbee** [comment]
Still working on implementing comments from my pull request, but here's the current state, and current live weather from my weather station shown in Google Home (cold today!):



<img width="337" alt="image" src="https://user-images.githubusercontent.com/4139136/216372326-2265aefc-7187-4280-bb56-8f5bd1ea8cde.png">

**Comment by Apollon77** [comment]
Cool

**Comment by Apollon77** [comment]
fixed by #235
