### ISSUE TITLE
cluster usage/creation

### ISSUE THREAD

**Issue by javierbarellano4v** [mfucci/node-matter#23]
In terms of cluster usage/creation, using the on/off cluster as an example

So, if I issue on/off cluster from a running instance of chip-tool in interactive mode, and I  had launched the following on a Raspberry Pi:

             matter -on "echo 255 > /sys/class/leds/led1/brightness" -off "echo 0 > /sys/class/leds/led1/brightness"

The LED light would turn on/off the Raspberry Pi in response to the chip-tool cluster (command).

Thanks.

Do I have have the behavior described correctly?

**Comment by mfucci** [comment]
I am not that familiar with chip-tool, but the overall flow should be this one:

- commission the device: chip-tool pairing onnetwork 222 20202021
- turn on / off the LED: chip-tool ???? (post the command on this thread if you have it)

You can test first with the Android app provided on this repository if you have an Android phone, this is what I use for testing.

Let me know if you have any issue: I will add how to use node-matter with chip-tool in node-matter documentation for everyone benefit...

**Comment by jdesai61** [comment]
@javierbarellano4v  Your understanding is correct. Once you pair as above, you can use cluster command, for example:
```
chip-tool onoff toggle 222 1
```
I have tested this and it works... Since there is no persistence in node-matter, but chip-tool has persistence, if you restart node-matter, you have to use
```
chip-tool pairing unpair 222
and/or
chip-tool storage clear-all
```

**Comment by mfucci** [comment]
Updated the doc in: https://github.com/mfucci/node-matter/pull/24
When it is merged, I think this ticket can be closed.

**Comment by mfucci** [comment]
Merged

**Comment by javierbarellano4v** [comment]
I know this is closed now... 

...but just wanted to thank @jdesai61 and @mfucci!
