### ISSUE TITLE
OSX  support

### ISSUE THREAD

**Issue by vves** [mfucci/node-matter#253]
While the library works on my linux issue, I and some others here in the US would like to use the library on an OSX instance.  Fix the network adapter for OSX.

**Comment by Apollon77** [comment]
What exactly is the issue? I use macos all the day with node-matter and it works.

Yes it is currently logging some error for "advertisements on wrong interfaces" but the github version already "ignores" these errors and it works.But yes selecting the right interfaces would be a topic for optimization

**Comment by vves** [comment]
It's a 3 line change to fix.  I'll post the pull request and you can decide if it's worth it.

**Comment by Apollon77** [comment]
Cool :-)
