### ISSUE TITLE
MDNS should ignore request that it can't handle

### ISSUE THREAD

**Issue by jdesai61** [mfucci/node-matter#29]
Currently my  home network has 192.168.1.x as primary sub-net.  However, it also contains other sub-nets and occasionally an MDNS request from another subnet is passed on to the primary subnet. The node-matter code simply dies when it receives a request from other subnets. It should just ignore MDNS request it can't handle and continue to run
```
/home/DadAdmin/node-matter/build/net/node/NetworkNode.js:47
        throw new Error(`Cannot find the device IP on the subnet containing ${remoteAddress}`);
        ^

Error: Cannot find the device IP on the subnet containing 192.168.122.1
    at NetworkNode.getIpMacOnInterface (/home/DadAdmin/node-matter/build/net/node/NetworkNode.js:47:15)
    at MdnsServer.handleDnsMessage (/home/DadAdmin/node-matter/build/mdns/MdnsServer.js:34:42)
    at /home/DadAdmin/node-matter/build/mdns/MdnsServer.js:26:63
    at /home/DadAdmin/node-matter/build/net/UdpMulticastServer.js:31:66
    at Socket.messageListener (/home/DadAdmin/node-matter/build/net/node/UdpSocketNode.js:45:62)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8)
```

**Comment by mfucci** [comment]
This should fix the issue: https://github.com/mfucci/node-matter/pull/30
I added an unit test to ensure this problem won't come back

**Comment by mfucci** [comment]
Merged into the branch [integration-test](https://github.com/mfucci/node-matter/tree/integration-test)
I will close this issue when the fix is merged with main.

**Comment by mfucci** [comment]
This is now merged in main

**Comment by jdesai61** [comment]
I am still noticing node-matter dying on handling some MDNS requests... Here is latest one. Notice that my subnet is 192.168.1.x, where as offending MDNS query comes from 192.168.122.1 (I don't have such a subnet so not sure why I am receiving these messages, but regardless, not-matter should just print an error message and continue instead of dying.
```
/home/DadAdmin/node-matter/build/net/node/NetworkNode.js:47
        throw new Error(`Cannot find the device IP on the subnet containing ${remoteAddress}`);
        ^

Error: Cannot find the device IP on the subnet containing 192.168.122.1
    at NetworkNode.getIpMacOnInterface (/home/DadAdmin/node-matter/build/net/node/NetworkNode.js:47:15)
    at MdnsServer.handleDnsMessage (/home/DadAdmin/node-matter/build/mdns/MdnsServer.js:34:36)
    at /home/DadAdmin/node-matter/build/mdns/MdnsServer.js:26:63
    at /home/DadAdmin/node-matter/build/net/UdpMulticastServer.js:31:66
    at Socket.messageListener (/home/DadAdmin/node-matter/build/net/node/UdpSocketNode.js:45:62)
    at Socket.emit (node:events:513:28)
    at UDP.onMessage [as onmessage] (node:dgram:922:8)
```

**Comment by mfucci** [comment]
Oups, my bad: I wrote an unit test for this using a fake network provider but I forgot to update the node implementation of the network provider.

Should be fixed now with: https://github.com/mfucci/node-matter/pull/49

**Comment by mfucci** [comment]
This is now merged in main
