### ISSUE TITLE
It would be nice to support Device Discovery - Commissionable Node Discovery using MDNS

### ISSUE THREAD

**Issue by jdesai61** [mfucci/node-matter#8]
It would be nice to support Device Discovery - Commissionable Node Discovery using MDNS, so that one could use a command like

chip-tool pairing onnetwork 222 20202021

rather than using device IP address/port ("chip-tool pairing ethernet 222 20202021 3840 192.168.1.28 5540")

**Comment by jdesai61** [comment]
I have added the required support for basic discovery. With the attached change, I can now discover device using "chip-tool pairing onnetwork 222 20202021".

**Comment by jdesai61** [comment]
I have created two separate issues - one for optional/required fields and another for HA integration

**Comment by mfucci** [comment]
Thanks!
I am now back in the US and I have recovered from the jetlag, so I will address those issues this week.

**Comment by jdesai61** [comment]
The latest refactor code does not seem to include publishing the _matterc._udp.local records (in the MdnsServer constructor from my pull request).  Where should that be added? In the new scheme of things, I can't find a proper place.

**Comment by mfucci** [comment]
This is now fixed with https://github.com/mfucci/node-matter/pull/15
