### ISSUE TITLE
if it can use for  matter bridge  server?

### ISSUE THREAD

**Issue by 1161853339** [mfucci/node-matter#88]

**Comment by Apollon77** [comment]
Can you please add some more content to your question?

If the question is if this library can be used to provide a Matter compatible device server to offer multiple bridged devices, the the answer is:
* Right now: no
* Is it planned that this is possible: Yes

If you want to collaborate to add support please check out the "DIscussions" senctionsabout implementing the missing Matter clusters and see if you can support here.

**Comment by mfucci** [comment]
See https://github.com/mfucci/node-matter/discussions/45 for the current cluster support.

Right now this can be used as a bridge server to control an on / off device, if it can controlled from the command line:

`matter -on "echo 255 > /sys/class/leds/led1/brightness" -off "echo 0 > /sys/class/leds/led1/brightness"`

This will start a Matter server that can turn on / off the LED on the raspberry Pi, but any other shell commands can be issued instead.

We are working on supporting more clusters that will allow to control other device types and we are welcoming contributors to implement specific bridges (BLE, Zigbee, etc...)

Closing this issue, please continue the discussion on the forum if you are interested in helping or testing!
